env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules: 
  no-unused-vars: 1
  no-console: 0
  import/extensions: 0
